@host = http://localhost:5045

### Listar todos os jogos
GET {{host}}/games
Accept: application/json

### Obter jogo específico por chave
GET {{host}}/games/850dc5df-9aea-4dd4-a53d-de4938104024
Accept: application/json

### Criar novo jogo
POST {{host}}/games
Content-Type: application/json

{
  "title": "The Legend of Zelda: Breath of the Wild",
  "description": "Um jogo de aventura e ação em um vasto mundo aberto"
}

### Atualizar jogo existente
PUT {{host}}/games/6924a7e7-1788-440b-8358-d9cd237fd467
Content-Type: application/json

{
  "title": "The Legend of Zelda: Breath of the Wild (Atualizado)",
  "description": "Versão completa do aclamado jogo de aventura em mundo aberto com todas as DLCs"
}

### Excluir jogo
DELETE {{host}}/games/6924a7e7-1788-440b-8358-d9cd237fd467
