@FCG.API_HostAddress = http://localhost:5045

GET {{FCG.API_HostAddress}}/users?search=test
Accept: application/json

POST {{FCG.API_HostAddress}}/users/
Accept: application/json
Content-Type: application/json
{
  "fistName": "John",
  "lastName": "Doe"
}
###
