@FCG.API_HostAddress = http://localhost:5045
@UserKey = paste_here
@AdminBearerToken = Bearer paste_here
@UserBearerToken = Bearer paste_here

### Login as admin
POST {{FCG.API_HostAddress}}/auth/login/
Accept: application/json
Content-Type: application/json
{
  "email": "admin@fcg.test.com.br",
  "password": "adm@demoPass312"
}

### Login as user
POST {{FCG.API_HostAddress}}/auth/login/
Accept: application/json
Content-Type: application/json
{
  "email": "user@fcg.test.com.br",
  "password": "usr@demoPass312"
}

### Search users by name (admin only)
GET {{FCG.API_HostAddress}}/users?search=jo
Authorization: {{AdminBearerToken}}
Accept: application/json

### Get user details by key (user)
GET {{FCG.API_HostAddress}}/users/{{UserKey}}
Authorization: {{UserBearerToken}}
Accept: application/json

### Create a new user (admin only)
POST {{FCG.API_HostAddress}}/users/
Authorization: {{AdminBearerToken}}
Accept: application/json
Content-Type: application/json
{
  "fullName": "John Doe",
  "email": "john.doe@email.com",
  "password": "FX9v&6sKx8<6"
}

### Update user details (admin only)
PUT {{FCG.API_HostAddress}}/users/{{UserKey}}
Authorization: {{AdminBearerToken}}
Accept: application/json
Content-Type: application/json
{
  "fullName": "John Ricardo Doe",
  "email": "john.doe@email.com"
}

### Delete a user (admin only)
DELETE {{FCG.API_HostAddress}}/users/{{UserKey}}
Authorization: {{AdminBearerToken}}
Accept: application/json

### Search catalogs by name (user)
GET {{FCG.API_HostAddress}}/catalogs?name=cloud
Authorization: {{UserBearerToken}}
Accept: application/json

### Get catalog details by id (user)
GET {{FCG.API_HostAddress}}/catalogs/{{$guid}}
Authorization: {{UserBearerToken}}
Accept: application/json

### Create a new catalog (admin only)
POST {{FCG.API_HostAddress}}/catalogs/
Authorization: {{AdminBearerToken}}
Accept: application/json
Content-Type: application/json
{
  "name": "Cloud",
  "description": "Azure Functions..."
}

### Update catalog details (admin only)
PUT {{FCG.API_HostAddress}}/catalogs/{{$guid}}
Authorization: {{AdminBearerToken}}
Accept: application/json
Content-Type: application/json
{
  "name": "Cloud",
  "description": "Azure Functions Updated..."
}

### Delete a catalog (admin only)
DELETE {{FCG.API_HostAddress}}/catalogs/{{$guid}}
Authorization: {{AdminBearerToken}}
Accept: application/json

### Search games in a catalog by title (user)
GET {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games?title=azure
Authorization: {{UserBearerToken}}
Accept: application/json

### Get game details by id in a catalog (user)
GET {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/{{$guid}}
Authorization: {{UserBearerToken}}
Accept: application/json

### Create a new game in a catalog (admin only)
POST {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/
Authorization: {{AdminBearerToken}}
Accept: application/json
Content-Type: application/json
{
  "title": "The Legend of Zelda: Breath of the Wild",
  "description": "Um jogo de aventura e ação em um vasto mundo aberto"
}

### Add evaluation to a game (user)
POST {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/{{$guid}}/evaluations
Authorization: {{UserBearerToken}}
Accept: application/json
Content-Type: application/json
{
  "stars": 5,
  "comment": "I've learned a lot with this game :)"
}

### Get evaluations for a game (user)
GET {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/{{$guid}}/evaluations
Authorization: {{UserBearerToken}}
Accept: application/json

### Download a game (user)
GET {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/{{$guid}}/download
Authorization: {{UserBearerToken}}
Accept: application/json

### Update game details (admin only)
PUT {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/{{$guid}}
Authorization: {{AdminBearerToken}}
Accept: application/json
Content-Type: application/json
{
  "title": "The Legend of Zelda: Breath of the Wild (Atualizado)",
  "description": "Versão completa do aclamado jogo de aventura em mundo aberto com todas as DLCs"
}

### Delete a game from a catalog (admin only)
DELETE {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/{{$guid}}
Authorization: {{AdminBearerToken}}
Accept: application/json
