@FCG.API_HostAddress = http://localhost:5045
@UserKey = fb39f42b-b85d-4d10-9a6a-ad79c474f02c

GET {{FCG.API_HostAddress}}/users?search=jo
Accept: application/json

###
GET {{FCG.API_HostAddress}}/users/{{UserKey}}
Accept: application/json

###
POST {{FCG.API_HostAddress}}/users/
Accept: application/json
Content-Type: application/json
{
  "fullName": "John Doe",
  "email": "john.doe@email.com",
  "password": "FX9v&6sKx8<6"
}

###
PUT {{FCG.API_HostAddress}}/users/{{UserKey}}
Accept: application/json
Content-Type: application/json
{
  "fullName": "John Ricardo Doe",
  "email": "john.doe@email.com"
}

###
DELETE {{FCG.API_HostAddress}}/users/{{UserKey}}
Accept: application/json

###
GET {{FCG.API_HostAddress}}/catalogs?search=Cotia
Accept: application/json

###
GET {{FCG.API_HostAddress}}/catalogs/{{$guid}}
Accept: application/json

###
POST {{FCG.API_HostAddress}}/catalogs/
Accept: application/json
Content-Type: application/json
{
  "name": "Cloud",
  "description": "Azure Functions..."
}

###
PUT {{FCG.API_HostAddress}}/catalogs/{{$guid}}
Accept: application/json
Content-Type: application/json
{
  "name": "Cloud",
  "description": "Azure Functions Updated..."
}

###
DELETE {{FCG.API_HostAddress}}/catalogs/{{$guid}}
Accept: application/json

###
GET {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games?title=azure
Accept: application/json

###
GET {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/{{$guid}}
Accept: application/json

###
POST {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/
Accept: application/json
Content-Type: application/json
{
  "title": "Triggers in Azure",
  "description": "Triggers in practice..."
}

###
POST {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/{{$guid}}/evaluate
Accept: application/json
Content-Type: application/json
{
  "stars": 5,
  "comment": "I've learned a lot with this game :)"
}

###
GET {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/{{$guid}}/download
Accept: application/json

###
PUT {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/{{$guid}}
Accept: application/json
Content-Type: application/json
{
  "title": "Triggers in Azure",
  "description": "Triggers in practice updated..."
}

###
DELETE {{FCG.API_HostAddress}}/catalogs/{{$guid}}/games/{{$guid}}
Accept: application/json
